# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField(db_index=True)),
                ('maturity_date', models.DateField(db_index=True)),
                ('maturity_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CLOSED_PREMATURELY', 'Closed prematurely')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('scheme_type', models.CharField(choices=[('FD', 'Fixed deposit'), ('RD', 'Recurring deposit')], db_index=True, max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('min_tenure_months', models.PositiveSmallIntegerField()),
                ('max_tenure_months', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
