# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('deposits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='linked_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='accounts.bankaccount'),
        ),
        migrations.AddConstraint(
            model_name='depositscheme',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='depscheme_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='depositscheme',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gt', 0)), name='depscheme_min_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='depositscheme',
            constraint=models.CheckConstraint(condition=models.Q(('max_tenure_months__gte', models.F('min_tenure_months'))), name='depscheme_tenure_range'),
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='deposits.depositscheme'),
        ),
        migrations.AddConstraint(
            model_name='depositaccount',
            constraint=models.CheckConstraint(condition=models.Q(('maturity_date__gt', models.F('start_date'))), name='deposit_maturity_after_start'),
        ),
        migrations.AddConstraint(
            model_name='depositaccount',
            constraint=models.CheckConstraint(condition=models.Q(('maturity_amount__gte', 0)), name='deposit_maturity_gte_0'),
        ),
    ]
