# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=10, unique=True)),
                ('branch_name', models.CharField(db_index=True, max_length=150)),
                ('ifsc_code', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Enter a valid IFSC (e.g. BNBK0001234).')])),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit pincode.')])),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('manager_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relation', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('percentage_share', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('min_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['type_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_balance__gte', 0)), name='accounttype_min_balance_gte_0'), models.CheckConstraint(condition=models.Q(('interest_rate__isnull', True), ('interest_rate__gte', 0), _connector='OR'), name='accounttype_interest_rate_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Account number must be 11 digits.')])),
                ('balance', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=18)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accounttype')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
