# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to='accounts.bankaccount'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='bankaccount_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='bankaccount_available_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_balance__gte', 0)), name='bankaccount_minimum_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='nominee',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_share__gte', 1), ('percentage_share__lte', 100)), name='nominee_share_1_100'),
        ),
    ]
