services:
  - type: web
    name: bharat-nidhi-bank
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEMO_SHOW_OTP
        value: "True"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: bnb-postgres
          property: connectionString

databases:
  - name: bnb-postgres
    plan: free
    databaseName: bharat_nidhi_bank
    user: bnb_admin
