# Generated by Django 5.2.17 on 2026-09-28 05:45

import apps.core.utils
import apps.core.validators
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{6,20}$', 'Username must be 6-20 letters/digits with no spaces.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter a 10-digit mobile number starting with 6-9.')])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current'), ('CORRESPONDENCE', 'Correspondence')], db_index=True, max_length=20)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit pincode.')])),
                ('country', models.CharField(default='India', max_length=100)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(default=apps.core.utils.generate_customer_number, max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(validators=[apps.core.validators.validate_min_age])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$', 'Enter a valid PAN (e.g. ABCDE1234F).')])),
                ('aadhaar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be 12 digits.')])),
                ('address_proof_type', models.CharField(blank=True, default='', max_length=50)),
                ('address_proof_number', models.CharField(blank=True, default='', max_length=50)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('documents_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to='users.employeeprofile')),
            ],
            options={
                'verbose_name': 'KYC profile',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('TRANSFER', 'Transfer'), ('BENEFICIARY_ADD', 'Add beneficiary'), ('PASSWORD_RESET', 'Password reset'), ('CARD_ACTION', 'Card action')], db_index=True, max_length=30)),
                ('hashed_otp', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=True)),
                ('registered_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter a 10-digit mobile number starting with 6-9.')])),
                ('registered_email', models.EmailField(max_length=254)),
                ('login_alerts', models.BooleanField(default=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'security settings',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='users_user_username_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('annual_income__gte', 0)), name='customer_income_gte_0'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'purpose', '-created_at'], name='otp_user_purpose_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='otp_attempts_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='otp_expires_after_created'),
        ),
    ]
