# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_enabled', models.BooleanField(default=True)),
                ('online_enabled', models.BooleanField(default=True)),
                ('international_enabled', models.BooleanField(default=False)),
                ('contactless_enabled', models.BooleanField(default=True)),
                ('daily_atm_limit', models.DecimalField(decimal_places=2, default=50000, max_digits=18)),
                ('daily_pos_limit', models.DecimalField(decimal_places=2, default=100000, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'card settings',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_reference', models.CharField(max_length=30, unique=True)),
                ('last_four', models.CharField(db_index=True, max_length=4)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], db_index=True, max_length=10)),
                ('name_on_card', models.CharField(max_length=150)),
                ('expiry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('TEMPORARILY_DISABLED', 'Temporarily disabled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('issue_date', models.DateField()),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='accounts.bankaccount')),
            ],
        ),
    ]
