# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='cardsettings',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='cards.card'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('limit_amount__gte', 0)), name='card_limit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='cardsettings',
            constraint=models.CheckConstraint(condition=models.Q(('daily_atm_limit__gte', 0), ('daily_pos_limit__gte', 0)), name='cardsettings_limits_gte_0'),
        ),
    ]
