# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_accounts', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_account', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='transactions.transfer'),
        ),
        migrations.AddConstraint(
            model_name='loantype',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='loantype_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='loantype',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gte', 0), ('max_amount__gte', models.F('min_amount'))), name='loantype_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='loantype',
            constraint=models.CheckConstraint(condition=models.Q(('tenure_min__gt', 0), ('tenure_max__gte', models.F('tenure_min'))), name='loantype_tenure_range'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loantype'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(condition=models.Q(('disbursed_amount__gt', 0), ('emi_amount__gt', 0)), name='loanacct_positive'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.UniqueConstraint(fields=('loan_account', 'installment_no'), name='uniq_installment_no'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount_requested__gt', 0), ('tenure_months__gt', 0)), name='loanapp_positive'),
        ),
    ]
