# Generated by Django 5.2.17 on 2026-09-28 05:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(db_index=True, max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(db_index=True, max_length=16)),
                ('ifsc_code', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Enter a valid IFSC (e.g. BNBK0001234).')])),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('beneficiary_type', models.CharField(choices=[('INTERNAL', 'Bharat Nidhi Bank'), ('EXTERNAL', 'Other bank (simulated)')], db_index=True, max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'beneficiaries',
                'ordering': ['beneficiary_name'],
            },
        ),
    ]
